- pom.xml
maven-dependency-plugin to 2.10
maven-gpg-plugin to 1.6
Since m2e only applies to eclipse and some edge case issues result in
warnings, move into a profile to protect from that condition.  This is activated
when m2e is present so nothing anyone needs to do in relation to this.
> Profile m2e and update plugins

- pom.xml
License plugin provides easy way to update license headers.  Configured to run for java only and only when license.txt is present in root of project component being built.
Updated maven-enforcer-plugin to 1.4
Move jarjar execution filter from mybatis3 to parent and placed into profile with others.
> Added license plugin, updated enforcer plugin, and moved jarjar execution filter

- pom.xml
Before merging this in, this needs a slight discussion.  With cobertura being removed and site deploy changing, its important every mybatis module get the updates all at once.  Initially, I'm putting up the parent and mybatis-3.  Once these are approved as go forwards, I'll go through remainder and start merging them all at once.
Check out usage of 'mvn site:deploy' as done to the following to verify this is what is needed.
http://hazendaz.github.io/parent/
http://hazendaz.github.io/mybatis-3/
The above are on my fork.  The real PR will be targetted for mybatis gh-pages.
The steps to perform this are pretty simple.
'mvn site' will continue to build the site out and should be run before a deploy.  This is local only.
'mvn site:deploy' will deploy out to mybatis gh site pages.
In …
> Use sonatype parent, remove cobertura, use different site deploy

- README.md
- pom.xml
sonatype oss-parent is deprecated.  This is noted on sonatype site.  Mybatis already followed release separately before this was introduced so this shouldn't be that bad.  The distribution elements are now directly added.
> Replace OSS Parent and update versions

- pom.xml
Currently, maven site is fail on mybatis project as follows:
```
$ mvn site
...
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.5.1:site (default-site) on project mybatis: Execution default-site of goal org.apache.maven.plugins:maven-site-plugin:3.5.1:site failed: Invalid byte tag in constant pool: 18 -> [Help 1]
...
```
> Update clirr-maven-plugin to 2.8 for support Java 8 byte code

- pom.xml
"report" is a reporting goal, not a build goal.  If necessary,
configurations to "report" should be made under the reporting section of
the pom.  There's no need to add it in under reporting in the parent
because it is executed automatically by the site goal.
Having the goal configured here causes maven to build the jacoco site
during the build which can cause problems for downstream projects that
might want to change how the jacoco site is built.
> Jacoco report goal is incorrectly configured

- pom.xml
- holds eclipse formatting rules for use with eclipse formatter plugin -
> [pom] Update build-tools to 1.1.3

- pom.xml
It's time for maven 3.2.5 given...
3.2.5 - java 6
3.3.x - java 7
3.5.0 - java 7
So three levels in line with support from other platforms like travis ci.
> Update dependencies and fix jacoco reporting aggregation

- pom.xml
This cut includes a 4 space variation of the 2 space used by mybatis.  More specifically this one is for the generator that uses 4 spaces but currently does not have this live turned on due to level of changes.
> [pom] Update build-tools to 1.1.4

- pom.xml
Fixes #88 
Not only was the wrong thing used, it never showed up as a problem as it was deprecated long ago and isn't even used internally.  Beyond that, for a long time I had noticed we had some find bug files in the target directory.  As it turns out our normal confirmation was wrong and we were missing the actual intended setting for findbugsXmlOutputDirectory.  So now this works properly.
> [pom] Correct findbugs configuration - fixes #88

- pom.xml
Findbugs has become defunct.  As a result, a new drop in place project called spotbugs is taking it's place.  As such the existing maven plugin for findbugs easily converts to use findbugs with little work.  While I'm trying to get traction on getting the original findbugs maven plugin updated, this introduction here will serve for early testing and maybe even final use if no traction is made.  As any underlying projects switch to this parent that define findbugs, the group/artifact will need to chage but all else will work the same.
Update: Checkstyle project is going to start using spotbugs-maven-plugin as well as others.  Testing flushed out an issue in upgrades I did so now version 3.0.6 is current with fixes.  Therefore this will no longer serve as testing area since that project is …
> [pom] Use spotbugs-maven-pugin 3.0.6

- pom.xml
The current version fails when running on JDK 9. Enforcer plugin version
3.0.0-M1 runs fine in JDK 9.
> Upgrade enforcer plugin version to 3.0.0-M1

- pom.xml
This allows proper detection of junit (so we don't skip junit 4 tests for example) and allows the project to build correctly using jdk 10
> Make build work with jdk 10 and use autodetection of surefire provider

- pom.xml
If you specify an argument for Surefire, then you must also include the
${argLine} property from JaCoCo.
> Fix JaCoCo Integration with Surefire

- pom.xml
This assists with ensuring we use more modern java usage throughout.  I have downgraded this to simply throw errors but not prevent builds as it will take some time to verify no issues throughout code bases.  There is exactly one item in mybatis-core that needs a patch due to this so it ignores the checks and I suspect there might be some in other modules.  For now though this is a welcome addition I've been otherwise using elsewhere most of 2018 to great success.
> Introduction of modernizer plugin

- pom.xml
The jacoco 0.8.5 is first version that support JDK 13 officially and support JDK 14 experimentally. 
For details, see https://github.com/jacoco/jacoco/releases/tag/v0.8.5.
> Update to jacoco 0.8.5

- pom.xml
The javadoctype setting can be adjusted as needed by overriding property.  It's set to -html5 which is generally going to be acceptable but yet to be tested across all of mybatis.  If issue is encountered, simply se that to -html4 or remove it.  Given this is for jdk 9 and above it's scope is currently limited.
mybatis had some slow running tests.  During junit 5 migrations, it was enhanced to run some tests on travis only. Bring that logic up so all of mybatis can benefit from that.
Add in profile to allow for easy way to manually sort the poms to comply with maven layout.
> Raise up jdk9on javadocType setting, junit 5 travis only run, and add support for pom sorting

- pom.xml
bug in 1.2.3 caused checkstyle to fail run.  This corrects the issue.
> [pom] Bump build-tools to 1.2.4

- pom.xml
partial fix for jdk 15 support.  Still need jacoco at minimum for the core of mybatis.
> [pom] Override bundle dependency plugin to 5.1.0

- pom.xml
Move git.commit.id to instructions as it fails to pick up properly otherwise.  Removed from jar.  Javadoc and Source are ok.
> [pom] Resolve git.commit.id issue with bundle plugin

- pom.xml
optimize is deprecated and no longer does anything with javac.  add parameters to provide usable data for reflection.
> Remove optimize and add parameters to compiler plugin

- .github/workflows/ci.yaml
- pom.xml
Previously, this only enforced jdk 11 or above.  The other values didn't really do anything other than indicate our intended support levels.  New setup will force any 11, any 17, any 19, or any 20 and block all others.
Fixes #401
> [pom] Lock down version range in more concise way

- pom.xml
Reworked mybatis-3 to just directly work off the property setting being used.  The profile just provided another way to set that which is not necessary.  Further when attempted to use from the parent, maven resolved incorrectly from our expectations.  Therefore removing it entirely.
> [pom] Remove the profile for ci as unnecessary

- .github/workflows/site.yaml
- pom.xml
on bnd-maven-plugin, it does not provide 'Include-Resource' and the 'Tool' goes unlisted.  I tried to make that show up and can get the NOTICE/LICENSE but not any properties as I see used on many now.  However those point local to the project so not sure how valuable they were to start with.
> Add site GHA and migrate maven bundle plugin to bnd-maven-plugin
